### ISSUE TITLE
Withdrawal from Polygon to Ethereum Stuck

### ISSUE THREAD

**Issue by rottenbeach** [maticnetwork/matic.js#211]
Hi,

I was testing bridging Ether to Polygon for use in DeFi and using the Matic Wallet bridge from Ethereum to Polygon was successful. However, on my test of withdrawing back to Ethereum the transaction was processed but the Ether never reached my Metamask wallet. 

Transaction ID here: https://etherscan.io/tx/0x31b078face2ec2b5dbe2d3a419e0118dac4bb4e07bfc0ce83c5e1b88c65c4dfa

In the Polygon Discord, this seems to be a recurring problem. It has been said these can be 
"manually pulled" by creating a new contract but I am not skilled in doing so. I am less concerned about the Ether lost and more concerned about this being a problem in general as I have other assets like Stablecoins and other Erc-20 tokens already on the Polygon network that I will need to withdraw in the near future. For reference, I have also submitted a Ticket to Polygon, ID # 6185. Thank you

Edit:

Here is a Doc with all the transaction ID's and screencaps showing my Ethereum balance decreasing on deposit but not increasing on withdrawal. 

https://docs.google.com/document/d/12tkir1okq_WxpUH82ZGrf8Y85A_QIbku7AR5CxVr654/edit?usp=sharing

**Comment by MaticParvez** [comment]
Hello ,

We see that you have successfully received the tokens. Since you are checking on the day to day balance change the same isn't reflecting you the change in balance.I have attached a screenshot which shows that there was a Deposit and withdrawal transaction.
If you are further queries to this please raise a support ticket with all details and team will assist you.
<img width="1364" alt="Screenshot 2021-06-07 at 1 17 40 PM" src="https://user-images.githubusercontent.com/77219419/120979030-c5a4da00-c792-11eb-9907-2892825ac16e.png">

![image](https://user-images.githubusercontent.com/77219419/120978525-326ba480-c792-11eb-9f11-5c7642fd2d2e.png)

**Comment by officelinebacker** [comment]
Hello, 

I had what appears to be this same issue, around the same time. Tokens burned, no call through the other side. 
Wallet: 0xE7C64c3823997F5993c059D2C20324E033566903
TX: 0x4320b8903ae0b6670ab530f3eabcd4406db79aa14f381efbf6e31aa15019e74c 
Token: ALCX 
Qty: 1.198362509659974952

I was told on the matic form how to solve it, < https://forum.matic.network/t/missing-bridge-transaction-burned-tokens/1058/12>  though I haven't worked in the code so am a bit stuck. Any help would be appreciated.

**Comment by playsnook** [comment]
Use calling contracts: https://docs.matic.network/docs/develop/ethereum-matic/pos/calling-contracts/erc20#exit
I experienced the same problem, then moved to using calls on contracts themselves and using maticPOSClient only to encode exit call data.
