### ISSUE TITLE
Approval for different address than the one who handles transaction

### ISSUE THREAD

**Issue by ZackMcClary34** [maticnetwork/matic.js#269]
I am using the sample node project (https://github.com/maticnetwork/pos-plasma-tutorial) to move some ZkGo from etherium Goerli network to polygon Mumbai network. The "Deposit" feature calls approve to add an allowance for address "0xdD6596F2029e6233DEFfaCa316e6A95217d4Dc34" . But then the "depositFor" that is called uses the "transferFrom" and checks the allowance of address "37c3bfc05d5ebf9ebb3ff80ce0bd0133bf221bc8" . Shouldn't those be the same addresses? Here are some sample transactions moving 0 ZkGo. I was only able to get a transaction of "1" to work by manually approving an allowance for that second address. Please provide an explanation or direct me to help. Thanks so much.

https://goerli.etherscan.io/tx/0xca75510d7a41acfd3933aee7ddf90732ca5aa74a5433e8611ce4afe40022cbf3

https://goerli.etherscan.io/tx/0x60b8fee0eac5f8e93d24200945bbe1bd660306a017297f4f9361bbd9df8a39d1

**Comment by ujjwalguptaofficial** [comment]
could you show me your code please ? 

But yes approval and deposit both should be done on the same contract. You are interacting with two predicate address - 

1. "ERC20PredicateProxy": "0xdD6596F2029e6233DEFfaCa316e6A95217d4Dc34",
2. "MintableERC20PredicateProxy": "0x37c3bfC05d5ebF9EBb3FF80ce0bd0133Bf221BC8",

since `ZackTalonICO2` is mintable token, so "MintableERC20PredicateProxy" is the right predicate.

If you will look at `approveErc20` method in matic.js - https://github.com/maticnetwork/matic.js/blob/eb24516cdeb7bc4ec3cc607ffe4b6a15fec52d86/src/root/POSRootChainManager.ts#L141

the predicate address is calculated in run time and the value will be - "MintableERC20PredicateProxy" 

and in case of `depositFor` method call - predicate address is also calculated same way - https://goerli.etherscan.io/address/0x0d2ae21bf7e72f646ef8e1f2aa92edbd13588691#code#L1946

I hope this helps.
