### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'process.stderr.fd')

### ISSUE THREAD

**Issue by haianh130799** [maticnetwork/matic.js#281]
I'm install this package with yarn version 2.0.48 when init MaticPOSClient i catch error 
TypeError: undefined is not an object (evaluating 'process.stderr.fd')

**Comment by ujjwalgupta94** [comment]
nope only goerli is allowed for testnet

what do you mean by showing exactly error message. Matic.js use `web3.js` for contract call so mostly all the errors are from `web3.js` itself.


We are working on better version of `maticjs` , so that will help you a lot with better code and understanding. Probably will be launched by next week mostly.
